### ISSUE TITLE
StackOverflow During Code Generation

### ISSUE THREAD

**Issue by nicholascm** [oazapfts/oazapfts#507]
We're getting this error when generating code on the latest versions using this library. 
We are using @rtk-query/codgen-openapi to generate RTKQuery hooks from an open api config, where oazapfts is a dependency of that tool. 

Version of nodejs: v18.4.2 and 20.9.0 LTS
npm version 9.5.0

```shell
RangeError: Maximum call stack size exceeded
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at /Users/username/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:136:33
    at Array.map (<anonymous>)
    at refPathToPropertyPath (/Users/username/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:136:10)
    at ApiGenerator.resolve (/Users/username/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:289:22)
    at ApiGenerator.checkSchemaOnlyMode (/Users/harrisonbacordo/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:619:49)
    at /Users/username/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:639:38
    at Array.some (<anonymous>)
    at ApiGenerator.checkSchemaOnlyMode (/Users/harrisonbacordo/Projects/web-app/node_modules/oazapfts/lib/codegen/generate.js:639:14)
```

**Comment by lostdev** [comment]
Having the same issue here.

**Comment by Svudec** [comment]
I believe this PR should fix it: https://github.com/oazapfts/oazapfts/pull/489

**Comment by milotoor** [comment]
I'm sorry to report to that the new release does not resolve my problem, which appears to be identical to OP's. However, it does lead to new undesirable behavior. Instead of erroring with a "Maximum call stack size exceeded" message it now hangs and never completes. Running the codegen script took about 2.5 seconds on `@rtk-query/codegen-openapi@1.0` and is still running after 10 minutes using `@rtk-query/codegen-openapi@1.2` with `oazapfts@4.10.1`.

I have not yet dug into why that is. It seems that #489 is preventing an overflow from occurring when a data structure refers to itself; perhaps my issue is a circular reference between multiple data structures? Even if that were the case, though, I don't understand why the problem would now manifest in an infinite loop rather than infinite recursion.

**Comment by milotoor** [comment]
After doing a bit more digging, I'm not sure if the loop actually is infinite. It may just be really, really, really long and full of repeated work. Here is what the `history` object looks like at one point during execution:

```ts
[
  "#/components/schemas/PaymentMethod", // First history entry
  "#/components/schemas/SepaDebit",
  "#/components/schemas/GeneratedFrom",
  "#/components/schemas/Charge",
  "#/components/schemas/Invoice",
  "#/components/schemas/Quote",
  "#/components/schemas/Computed",
  "#/components/schemas/Recurring",
  "#/components/schemas/TotalDetails",
  "#/components/schemas/Breakdown",
  "#/components/schemas/Discount",
  "#/components/schemas/Customer",
  "#/components/schemas/SubscriptionCollection",
  "#/components/schemas/Subscription1",
  "#/components/schemas/SubscriptionSchedule",
  "#/components/schemas/Phase",
  "#/components/schemas/InvoiceSettings",
  "#/components/schemas/RenderingOptions",
  "#/components/schemas/JsonObject", // <-- extremely common reference within `stripe-java`
  "#/components/schemas/JsonArray",
  "#/components/schemas/JsonPrimitive",
  "#/components/schemas/JsonNull" // Most recent history entry
]
```

I believe that most of these references are from the `stripe-java` package (e.g. [here is the `PaymentMethod` object](https://www.javadoc.io/doc/com.stripe/stripe-java/19.28.0/index.html) at the root of the `history` object) and are mostly irrelevant to my application. Many, many objects in `stripe-java` refer to this `JsonObject`, which then refers to the `JsonArray`, `JsonPrimitive` and `JsonNull` types. Those types also refer to one another. As the process continues the `history` object will pop and push those several types repeatedly, and each time the `JsonObject` type is referred to the dance happens again. It goes like this:

```
... JsonObject
... JsonObject JsonArray
... JsonObject JsonArray JsonPrimitive
... JsonObject JsonArray JsonPrimitive JsonNull
... JsonObject JsonArray JsonNull
... JsonObject JsonArray JsonNull JsonPrimitive
... JsonObject JsonPrimitive
... JsonObject JsonPrimitive JsonArray
... JsonObject JsonPrimitive JsonArray JsonNull
... JsonObject JsonPrimitive JsonNull
... JsonObject JsonPrimitive JsonNull JsonArray
... JsonObject JsonNull
... JsonObject JsonNull JsonArray
... JsonObject JsonNull JsonArray JsonPrimitive
... JsonObject JsonNull JsonPrimitive
... JsonObject JsonNull JsonPrimitive JsonArray
```

This is a relatively small amount of work being repeated, it just happens over and over and over. More importantly, it illustrates how the lack of memoization is problematic. This long `history` object starts at the `PaymentMethod` type, which is itself referenced 14 times in my OpenAPI spec. That doesn't necessarily mean this entire recursive process will repeat itself 14 times, because some of the other references are themselves referred to by the `PaymentMethod` type or one of its various nested references. But if any of the other 14 references are _not_ referenced in the type-tree starting with the `PaymentMethod` root, the whole thing starts anew.

Memoization is the solution to this classical recursion problem. I'm not familiar at all with `oazapfts` (like the OP, it's a dependency of a dependency of mine, namely `@rtk-query/codegen-openapi`) and I have no idea to what extent memoization is included in the code already. To my unfamiliar eye, it seems like it could be added to the new `check` method by simply removing the [`history.delete` call on line 791](https://github.com/oazapfts/oazapfts/pull/489/files#diff-fed6cbb7bf4bf31afe5d3ec091e12aa2b8c3c83d394ff6a2e6d94f0f1ec7a5e0R791), but I don't know what the unintended consequences of doing so might be.

**Comment by bdm-k** [comment]
Hi @milotoor, can I download the OpenAPI Document you're using? I'd like to make sure that it can be compiled in a reasonable amount of time before I proceed to create a PR. If that's not feasible, we might need to ask you to test the pre-release.

**Comment by milotoor** [comment]
Hi @bdm-k, I'll ask if I can share the file but I suspect I won't be able to unfortunately. I'm more than happy to test the pre-release though!
